export const GET_PTC_PROFILE = 'GET_PTC_PROFILE';
export const GET_GOOGLE_PROFILE = 'GET_GOOGLE_PROFILE';
export const GOT_PROFILE = 'GOT_PROFILE';
export const ERROR_ON_PROFILE = 'ERROR_ON_PROFILE';
